services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3308:3306
    networks:
      - my_network
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/docker/data/redis
    command: redis-server --appendonly yes
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my_network
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - 5341:80
    networks:
      - my_network
    environment:
      - ACCEPT_EULA=Y
    SEQ_API_KEY: "DyfUIl5tkvhszhFsMapj"  

    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 3  

volumes:
  mysql_data:
  redis_data:

networks:
  my_network:
    driver: bridge