version: "3.9"
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "playticket123"  
      MYSQL_DATABASE: "Test"  
      MYSQL_USER: "playticket" 
      MYSQL_PASSWORD: "playticket123"  
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3308:3306

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/docker/data/redis
    command: redis-server --appendonly yes

volumes:
  mysql_data: 
  redis_data:
