// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayTicket.UserService.EntityFrameworkCore.DbCompliance;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace PlayTicket.UserService.Migrations
{
    [DbContext(typeof(DbComplainceDbContext))]
    [Migration("20241209113118_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PlayTicket.UserService.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_dttm");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext")
                        .HasColumnName("user_uid");

                    b.HasKey("Id");

                    b.ToTable("t_user", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
